import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zimri Tech Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        </link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        </link>
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet"></link>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="#0d3b66"  // Change to your desired color
          height={4}        // Adjust the height in pixels
          speed={800}       // Animation speed in milliseconds
          showSpinner={false} // Hide the loading spinner
          easing="ease"     // Animation easing

        />
        <Providers>
          <div className="px-2 sm:px-0">
            {children}
          </div>
        </Providers>
      </body>
    </html >
  );
}
